[package]
name = "neo-driver-repair"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
neo-device = { path = "../neo-device" }
neo-driverstore = { path = "../neo-driverstore" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
