[package]
name = "neo-debloat-probe"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
neo-debloat = { path = "../neo-debloat" }
neo-probe = { path = "../neo-probe" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
